export enum RouteKeyEnum {
  ROOT = "ROOT",
  PERSONAL_INFORMATION = "PERSONAL_INFORMATION",

  SYSTEM = "SYSTEM",
  ROLE_MANAGEMENT = "ROLE_MANAGEMENT",

  //   USER_MANAGEMENT = "USER_MANAGEMENT",
  //   INSTITUTION_MANAGEMENT = "INSTITUTION_MANAGEMENT",
  //   TOPO_MANAGEMENT = "TOPO_MANAGEMENT",
  //   TOPO_EDITOR = "TOPO_EDITOR",
  //   PERMISSION = "PERMISSION",
  //   DICT_MANAGEMENT = "DICT_MANAGEMENT",

  LOGIN = "LOGIN",
  PAGE_403 = "PAGE_403",
  PAGE_404 = "PAGE_404",
}
